# Generated by Django 6.0.7 on 2026-07-29 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_productvariant_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='featured',
            new_name='is_featured',
        ),
    ]
